language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t skygao/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true skygao/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker"
  env: "docker-env"
  bucket_name: "elasticbeanstalk-us-west-1-764476329573"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
